# Generated by Django 5.0.3 on 2024-03-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='astronomyshow',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='showsession',
            options={'ordering': ('-show_time',)},
        ),
        migrations.RemoveField(
            model_name='showtheme',
            name='astronomy_shows',
        ),
        migrations.AddField(
            model_name='astronomyshow',
            name='show_theme',
            field=models.ManyToManyField(related_name='astronomy_shows', to='planetarium.showtheme'),
        ),
        migrations.AlterField(
            model_name='astronomyshow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='showtheme',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
