# Generated by Django 5.0.3 on 2024-03-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0002_alter_astronomyshow_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('row', 'seat')},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('show_session', 'row', 'seat')},
        ),
    ]
