# Generated by Django 5.0.3 on 2024-03-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ("-created_at",)},
        ),
    ]
